CURRENTDATE="$(date +%Y-%m-%d)"

aws emr add-steps --cluster-id $(aws emr list-clusters --active --query 'Clusters[?Name==`polyglotDataNerd-spark-CCPA-production`].Id' --output text) --steps Type=Spark,Name=CCPA-Anonmyizer,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-gravy/customers/$CURRENTDATE/*","s3://polyglotDataNerd-bigdata-gravy/anonymized/customers/","gzip","gravy_users"]

#aws emr add-steps --cluster-id $(aws emr list-clusters --active --query 'Clusters[?Name==`polyglotDataNerd-spark-CCPA-production`].Id' --output text) --steps Type=Spark,Name=CCPA-Anonmyizer,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-gravy/customers/$CURRENTDATE/*","s3://polyglotDataNerd-bigdata-gravy/anonymized/customers/","orc","gravy_users"]

aws emr add-steps --cluster-id $(aws emr list-clusters --active --query 'Clusters[?Name==`polyglotDataNerd-spark-CCPA-production`].Id' --output text) --steps Type=Spark,Name=CCPA-Anonmyizer,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-levelup-east/datafeeds/sg_users/$CURRENTDATE/*","s3://polyglotDataNerd-bigdata-levelup-east/anonymized/sg_users/","gzip","levelup_users"]

#aws emr add-steps --cluster-id $(aws emr list-clusters --active --query 'Clusters[?Name==`polyglotDataNerd-spark-CCPA-production`].Id' --output text) --steps Type=Spark,Name=CCPA-Anonmyizer,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-levelup-east/datafeeds/sg_users/$CURRENTDATE/*","s3://polyglotDataNerd-bigdata-levelup-east/anonymized/sg_users/","orc","levelup_users"]

aws emr add-steps --cluster-id $(aws emr list-clusters --active --query 'Clusters[?Name==`polyglotDataNerd-spark-CCPA-production`].Id' --output text) --steps Type=Spark,Name=CCPA-Anonmyizer,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-mixpanel/iosprops/daily/transformed2/$CURRENTDATE2/*","s3://polyglotDataNerd-bigdata-mixpanel/anonymized/iosprops/transformed/","gzip","mixpanel_users"]

aws emr add-steps --cluster-id $(aws emr list-clusters --active --query 'Clusters[?Name==`polyglotDataNerd-spark-CCPA-production`].Id' --output text) --steps Type=Spark,Name=CCPA-Anonmyizer,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-mixpanel/web/transformed/$CURRENTDATE2/*","s3://polyglotDataNerd-bigdata-mixpanel/anonymized/web/transformed/","gzip","mixpanel_web"]

aws emr add-steps --cluster-id $(aws emr list-clusters --active --query 'Clusters[?Name==`polyglotDataNerd-spark-CCPA-production`].Id' --output text) --steps Type=Spark,Name=CCPA-Anonmyizer,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-kustomer/consumer/transformed/customer/$CURRENTDATE2/*","s3://polyglotDataNerd-bigdata-kustomer/anonymized/consumer/customer/transformed/","gzip","kustomer_customers"]

aws emr add-steps --cluster-id $(aws emr list-clusters --active --query 'Clusters[?Name==`polyglotDataNerd-spark-CCPA-production`].Id' --output text) --steps Type=Spark,Name=CCPA-Anonmyizer,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-yepchat/transformed/$CURRENTDATE2/*","s3://polyglotDataNerd-bigdata-yepchat/anonymized/transformed/","gzip","yepchat"]

CURRENTDATE2="$(date  +%Y-%m-%d -d "1 days ago")"

#JSON Anonmyizer MixPanel
aws emr add-steps --cluster-id $(aws emr list-clusters --active --query 'Clusters[?Name==`polyglotDataNerd-spark-CCPA-production`].Id' --output text) --steps Type=Spark,Name=CCPA-Anonmyizer,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.javacaller.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"polyglotDataNerd-bigdata-mixpanel","iosprops/daily/raw2/$CURRENTDATE/","mixpaneljson","polyglotDataNerd-bigdata-mixpanel","\$last_name\,\$first_name\,\$email\,\$phone"]

#JSON Anonmyizer YepChat
aws emr add-steps --cluster-id $(aws emr list-clusters --active --query 'Clusters[?Name==`polyglotDataNerd-spark-CCPA-production`].Id' --output text) --steps Type=Spark,Name=CCPA-Anonmyizer,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.javacaller.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"polyglotDataNerd-bigdata-yepchat","raw/$CURRENTDATE/","yepchatjson","polyglotDataNerd-bigdata-yepchat","first_name\,last_name\,mobile"]

#JSON Anonmyizer Kustomer
aws emr add-steps --cluster-id $(aws emr list-clusters --active --query 'Clusters[?Name==`polyglotDataNerd-spark-CCPA-production`].Id' --output text) --steps Type=Spark,Name=CCPA-Anonmyizer,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.javacaller.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"polyglotDataNerd-bigdata-kustomer","consumer/raw/$CURRENTDATE/","kustomerjson","polyglotDataNerd-bigdata-kustomer","emails\,firstName\,lastName\,name\,displayName\,preview"]


aws emr create-cluster --applications Name=Hadoop Name=Hive Name=Spark --tags 'VPC=vpc-0b57e4b3c93c1f2e0' 'name=polyglotDataNerd-spark-CCPA-ephemeral' 'Environment=production' 'Name=polyglotDataNerd-spark-CCPA-ephemeral' --ec2-attributes '{"KeyName":"sg-bigdata-proxy","AdditionalSlaveSecurityGroups":["sg-04bd133673c9e6436"],"InstanceProfile":"sg-EMR-role","ServiceAccessSecurityGroup":"sg-0a5ffff5608fff478","SubnetId":"subnet-05495ba617a541515","EmrManagedSlaveSecurityGroup":"sg-0ba826746a7863496","EmrManagedMasterSecurityGroup":"sg-0933f99b5350fb262","AdditionalMasterSecurityGroups":["sg-04bd133673c9e6436"]}' --release-label emr-5.25.0 --log-uri 's3n://polyglotDataNerd-bigdata-hadoop/' --instance-groups '[{"InstanceCount":1,"EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":100,"VolumeType":"io1","Iops":3000},"VolumesPerInstance":1}],"EbsOptimized":true},"InstanceGroupType":"MASTER","InstanceType":"r4.2xlarge","Name":"Master - 1"},{"InstanceCount":1,"EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":32,"VolumeType":"gp2"},"VolumesPerInstance":1}]},"InstanceGroupType":"CORE","InstanceType":"r4.2xlarge","Name":"Core - 2"}]' --configurations '[{"Classification":"spark","Properties":{"authenticate":"true","maximizeResourceAllocation":"true"}},{"Classification":"emrfs-site","Properties":{"fs.s3.serverSideEncryptionAlgorithm":"AES256","fs.s3.enableServerSideEncryption":"true"}},{"Classification":"jupyter-s3-conf","Properties":{"s3.persistence.bucket":"polyglotDataNerd-bigdata-utility","s3.persistence.enabled":"true"}}]' --auto-scaling-role EMR_AutoScaling_DefaultRole --ebs-root-volume-size 10 --service-role EMR_DefaultRole --enable-debugging --name 'polyglotDataNerd-spark-CCPA-ephemeral' --region us-west-2 --steps Type=Spark,Name=CCPA-Anonmyizer,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-levelup-east/datafeeds/sg_users/$CURRENTDATE/*","s3://polyglotDataNerd-bigdata-levelup-east/anonymized/sg_users/","gzip","levelup_users"] --auto-terminate

#emr CCPA testing cluster
CURRENTDATE="$(date +%Y-%m-%d)"

aws emr create-cluster --applications Name=Hadoop Name=Hive Name=Ganglia Name=Spark Name=Livy --tags 'name=polyglotDataNerd-spark-processor-testing' 'Environment=testing' 'Name=polyglotDataNerd-spark-CCPA-testing' --ec2-attributes '{"KeyName":"sg-bigdata-proxy","AdditionalSlaveSecurityGroups":["sg-0c08bd8a906d315c9"],"InstanceProfile":"sg-EMR-role","ServiceAccessSecurityGroup":"sg-0667aeb093c4cd43b","SubnetId":"subnet-0b96df7879c8dc10f","EmrManagedSlaveSecurityGroup":"sg-083ff6351703b69ca","EmrManagedMasterSecurityGroup":"sg-024ae8f3092bdd4be","AdditionalMasterSecurityGroups":["sg-0c08bd8a906d315c9"]}' --release-label emr-5.27.0 --log-uri 's3n://polyglotDataNerd-bigdata-hadoop/' --instance-groups '[{"InstanceCount":1,"EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":100,"VolumeType":"io1","Iops":3000},"VolumesPerInstance":1}],"EbsOptimized":true},"InstanceGroupType":"MASTER","InstanceType":"r4.2xlarge","Name":"Master - 1"},{"InstanceCount":9,"EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":32,"VolumeType":"gp2"},"VolumesPerInstance":1}]},"InstanceGroupType":"CORE","InstanceType":"r4.2xlarge","Name":"Core - 2"}]' --configurations '[{"Classification":"spark","Properties":{"authenticate":"true","maximizeResourceAllocation":"true"}},{"Classification":"emrfs-site","Properties":{"fs.s3.serverSideEncryptionAlgorithm":"AES256","fs.s3.enableServerSideEncryption":"true"}},{"Classification":"jupyter-s3-conf","Properties":{"s3.persistence.bucket":"polyglotDataNerd-bigdata-utility","s3.persistence.enabled":"true"}}]' --auto-scaling-role EMR_AutoScaling_DefaultRole --bootstrap-actions '[{"Path":"s3://polyglotDataNerd-bigdata-utility/emr/python_emr_modules.sh","Name":"Bootstrap action"}]' --ebs-root-volume-size 10 --service-role EMR_DefaultRole --enable-debugging --name 'polyglotDataNerd-spark-CCPA-testing' --scale-down-behavior TERMINATE_AT_TASK_COMPLETION --region us-west-2

#adding courrency level only works on new aws cli aws-cli/1.16.303 Python/3.7.0 Darwin/19.2.0 botocore/1.13.39
aws emr create-cluster --applications Name=Hadoop Name=Hive Name=Ganglia Name=Spark Name=Livy --tags 'VPC=vpc-0b57e4b3c93c1f2e0' 'name=polyglotDataNerd-spark-CCPA-production' 'Environment=production' 'Name=polyglotDataNerd-spark-CCPA-production' --ec2-attributes '{"KeyName":"sg-bigdata-proxy","AdditionalSlaveSecurityGroups":["sg-04bd133673c9e6436"],"InstanceProfile":"sg-EMR-role","ServiceAccessSecurityGroup":"sg-0a5ffff5608fff478","SubnetId":"subnet-05495ba617a541515","EmrManagedSlaveSecurityGroup":"sg-0ba826746a7863496","EmrManagedMasterSecurityGroup":"sg-0933f99b5350fb262","AdditionalMasterSecurityGroups":["sg-04bd133673c9e6436"]}' --release-label emr-5.28.0 --log-uri 's3n://polyglotDataNerd-bigdata-hadoop/' --instance-groups '[{"InstanceCount":1,"EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":100,"VolumeType":"io1","Iops":3000},"VolumesPerInstance":1}],"EbsOptimized":true},"InstanceGroupType":"MASTER","InstanceType":"r5d.24xlarge","Name":"Master - 1"},{"InstanceCount":2,"EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":32,"VolumeType":"gp2"},"VolumesPerInstance":1}]},"InstanceGroupType":"CORE","InstanceType":"r5d.12xlarge","Name":"Core - 2"}]' --configurations '[{"Classification":"spark","Properties":{"authenticate":"true","maximizeResourceAllocation":"true"}},{"Classification":"emrfs-site","Properties":{"fs.s3.serverSideEncryptionAlgorithm":"AES256","fs.s3.enableServerSideEncryption":"true"}},{"Classification":"jupyter-s3-conf","Properties":{"s3.persistence.bucket":"polyglotDataNerd-bigdata-utility","s3.persistence.enabled":"true"}}]' --auto-scaling-role EMR_AutoScaling_DefaultRole --bootstrap-actions '[{"Path":"s3://polyglotDataNerd-bigdata-utility/emr/python_emr_modules.sh","Name":"Bootstrap action"}]' --ebs-root-volume-size 10 --service-role EMR_DefaultRole --enable-debugging --name 'polyglotDataNerd-spark-CCPA-production' --scale-down-behavior TERMINATE_AT_TASK_COMPLETION --region us-west-2  --step-concurrency-level 50

aws emr modify-cluster --cluster-id $(aws emr list-clusters --active --query 'Clusters[?Name==`polyglotDataNerd-spark-CCPA-production`].Id' --output text) --step-concurrency-level 50

#emr CCPA cluster ephemeral
CURRENTDATE="$(date +%Y-%m-%d)"
CURRENTDATE2="$(date -v-1d +%Y-%m-%d)"

aws emr create-cluster --applications Name=Hadoop Name=Hive Name=Ganglia Name=Spark Name=Livy --tags 'VPC=vpc-0b57e4b3c93c1f2e0' 'name=polyglotDataNerd-spark-CCPA-production' 'Environment=production' 'Name=polyglotDataNerd-spark-CCPA-production' --ec2-attributes '{"KeyName":"sg-bigdata-proxy","AdditionalSlaveSecurityGroups":["sg-04bd133673c9e6436"],"InstanceProfile":"sg-EMR-role","ServiceAccessSecurityGroup":"sg-0a5ffff5608fff478","SubnetId":"subnet-05495ba617a541515","EmrManagedSlaveSecurityGroup":"sg-0ba826746a7863496","EmrManagedMasterSecurityGroup":"sg-0933f99b5350fb262","AdditionalMasterSecurityGroups":["sg-04bd133673c9e6436"]}' --release-label emr-5.28.0 --log-uri 's3n://polyglotDataNerd-bigdata-hadoop/' --instance-groups '[{"InstanceCount":1,"EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":100,"VolumeType":"io1","Iops":3000},"VolumesPerInstance":1}],"EbsOptimized":true},"InstanceGroupType":"MASTER","InstanceType":"r5d.24xlarge","Name":"Master - 1"},{"InstanceCount":2,"EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":32,"VolumeType":"gp2"},"VolumesPerInstance":1}]},"InstanceGroupType":"CORE","InstanceType":"r5d.12xlarge","Name":"Core - 2"}]' --configurations '[{"Classification":"spark","Properties":{"authenticate":"true","maximizeResourceAllocation":"true"}},{"Classification":"emrfs-site","Properties":{"fs.s3.serverSideEncryptionAlgorithm":"AES256","fs.s3.enableServerSideEncryption":"true"}},{"Classification":"jupyter-s3-conf","Properties":{"s3.persistence.bucket":"polyglotDataNerd-bigdata-utility","s3.persistence.enabled":"true"}}]' --auto-scaling-role EMR_AutoScaling_DefaultRole --bootstrap-actions '[{"Path":"s3://polyglotDataNerd-bigdata-utility/emr/python_emr_modules.sh","Name":"Bootstrap action"}]' --ebs-root-volume-size 10 --service-role EMR_DefaultRole --enable-debugging --name 'polyglotDataNerd-spark-CCPA-production' --scale-down-behavior TERMINATE_AT_TASK_COMPLETION --region us-west-2 \
--steps \
Type=Spark,Name=SPARK-Anonmyizer-gravyUsers,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-gravy/customers/$CURRENTDATE/*","s3://polyglotDataNerd-bigdata-gravy/anonymized/customers/","gzip","gravy_users"] \
Type=Spark,Name=SPARK-Anonmyizer-levelupUsers,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-levelup-east/datafeeds/sg_users/$CURRENTDATE/*","s3://polyglotDataNerd-bigdata-levelup-east/anonymized/sg_users/","gzip","levelup_users"] \
Type=Spark,Name=JAVA-Anonmyizer-mixpaneljson,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.javacaller.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"polyglotDataNerd-bigdata-mixpanel","iosprops/daily/raw2/$CURRENTDATE2/","mixpaneljson","polyglotDataNerd-bigdata-mixpanel","\$last_name\,\$first_name\,\$email\,\$phone"] \
Type=Spark,Name=JAVA-Anonmyizer-yepchatjson,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.javacaller.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"polyglotDataNerd-bigdata-yepchat","raw/$CURRENTDATE2/","yepchatjson","polyglotDataNerd-bigdata-yepchat","first_name\,last_name\,mobile"] \
Type=Spark,Name=JAVA-Anonmyizer-kustomerjson,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.javacaller.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"polyglotDataNerd-bigdata-kustomer","consumer/raw/$CURRENTDATE2/","kustomerjson","polyglotDataNerd-bigdata-kustomer","emails\,firstName\,lastName\,name\,displayName\,preview"] \
Type=Spark,Name=JAVA-Anonmyizer-qsrjson,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.javacaller.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"polyglotDataNerd-bigdata-qsr","consumer/raw/$CURRENTDATE2/","qsrjson","polyglotDataNerd-bigdata-qsr","customername\,server\,tablename"] \
Type=Spark,Name=SPARK-Anonmyizer-mixpanelUsers,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-mixpanel/iosprops/daily/transformed2/$CURRENTDATE2/*","s3://polyglotDataNerd-bigdata-mixpanel/anonymized/iosprops/transformed/","gzip","mixpanel_users"] \
Type=Spark,Name=SPARK-Anonmyizer-kustomerCustomers,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-kustomer/consumer/transformed/customer/$CURRENTDATE2/*","s3://polyglotDataNerd-bigdata-kustomer/anonymized/consumer/customer/transformed/","gzip","kustomer_customers"] \
Type=Spark,Name=SPARK-Anonmyizer-mixpanelWeb,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-mixpanel/web/transformed/$CURRENTDATE2/*","s3://polyglotDataNerd-bigdata-mixpanel/anonymized/web/transformed/","gzip","mixpanel_web"] \
Type=Spark,Name=SPARK-Anonmyizer-yepchat,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-yepchat/transformed/$CURRENTDATE2/*","s3://polyglotDataNerd-bigdata-yepchat/anonymized/transformed/","gzip","yepchat"] \
Type=Spark,Name=SPARK-Anonmyizer-qsr,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-qsr/consumer/transformed/$CURRENTDATE2/*","s3://polyglotDataNerd-bigdata-qsr/anonymized/consumer/transformed/","gzip","qsr"] \
--step-concurrency-level 50  --termination-protected  --auto-terminate

#deletion
aws emr create-cluster --applications Name=Hadoop Name=Hive Name=Ganglia Name=Spark Name=Livy --tags 'VPC=vpc-0b57e4b3c93c1f2e0' 'name=polyglotDataNerd-spark-CCPA-deletion' 'Environment=deletion' 'Name=polyglotDataNerd-spark-CCPA-deletion' --ec2-attributes '{"KeyName":"sg-bigdata-proxy","AdditionalSlaveSecurityGroups":["sg-04bd133673c9e6436"],"InstanceProfile":"sg-EMR-role","ServiceAccessSecurityGroup":"sg-0a5ffff5608fff478","SubnetId":"subnet-05495ba617a541515","EmrManagedSlaveSecurityGroup":"sg-0ba826746a7863496","EmrManagedMasterSecurityGroup":"sg-0933f99b5350fb262","AdditionalMasterSecurityGroups":["sg-04bd133673c9e6436"]}' --release-label emr-5.28.0 --log-uri 's3n://polyglotDataNerd-bigdata-hadoop/' --instance-groups '[{"InstanceCount":1,"EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":100,"VolumeType":"io1","Iops":3000},"VolumesPerInstance":1}],"EbsOptimized":true},"InstanceGroupType":"MASTER","InstanceType":"r5d.24xlarge","Name":"Master - 1"},{"InstanceCount":2,"EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":32,"VolumeType":"gp2"},"VolumesPerInstance":1}]},"InstanceGroupType":"CORE","InstanceType":"r5d.24xlarge","Name":"Core - 2"}]' --configurations '[{"Classification":"spark","Properties":{"authenticate":"true","maximizeResourceAllocation":"true"}},{"Classification":"emrfs-site","Properties":{"fs.s3.serverSideEncryptionAlgorithm":"AES256","fs.s3.enableServerSideEncryption":"true"}},{"Classification":"jupyter-s3-conf","Properties":{"s3.persistence.bucket":"polyglotDataNerd-bigdata-utility","s3.persistence.enabled":"true"}}]' --auto-scaling-role EMR_AutoScaling_DefaultRole --bootstrap-actions '[{"Path":"s3://polyglotDataNerd-bigdata-utility/emr/python_emr_modules.sh","Name":"Bootstrap action"}]' --ebs-root-volume-size 10 --service-role EMR_DefaultRole --enable-debugging --name 'polyglotDataNerd-spark-CCPA-deletion' --scale-down-behavior TERMINATE_AT_TASK_COMPLETION --region us-west-2 \
--steps \
Type=Spark,Name=SPARK-Delete-gravyUsers,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.deletor.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-private/gravy/customers/gzip/*","s3://polyglotDataNerd-bigdata-private/gravy/customers/","gzip","gravy_users_delete"] \
Type=Spark,Name=SPARK-Delete-levelupUsers,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.deletor.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-private/levelup/sg_users/gzip/*","s3://polyglotDataNerd-bigdata-private/levelup/sg_users/","gzip","levelup_users_delete"] \
Type=Spark,Name=SPARK-Delete-mixpanelIOSProps,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.deletor.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-private/mixpanel/iosprops/transformed/gzip/*","s3://polyglotDataNerd-bigdata-private/mixpanel/iosprops/transformed/","gzip","mixpanel_users_delete"] \
Type=Spark,Name=SPARK-Delete-mixpanelWeb,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.deletor.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-private/mixpanel/web/transformed/gzip/*","s3://polyglotDataNerd-bigdata-private/mixpanel/web/transformed/","gzip","mixpanel_web_delete"] \
Type=Spark,Name=SPARK-Delete-kustomerCustomers,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.deletor.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-private/kustomer/customer/transformed/gzip/*","s3://polyglotDataNerd-bigdata-private/kustomer/customer/transformed/","gzip","kustomer_customers_delete"] \
--step-concurrency-level 1  --termination-protected  --auto-terminate


#DynamoDB Bulk Spark Writer
CURRENTDATE="$(date +%Y-%m-%d)"

aws emr add-steps --cluster-id $(aws emr list-clusters --active --query 'Clusters[?Name==`polyglotDataNerd-spark-CCPA-production`].Id' --output text) --steps Type=Spark,Name=CCPA-Anonmyizer,ActionOnFailure=CONTINUE,Args=[--class,com.sg.ccpa.Loader,s3n://polyglotDataNerd-bigdata-utility/spark/poly-spark-ccpa/target/poly-spark-ccpa-1.0-production.jar,"s3://polyglotDataNerd-bigdata-unloads/sweettouch/id_service/$CURRENTDATE/*","placeholder","placeholder","writer"]

